### ISSUE TITLE
Fix: Inconsistent Vertical Alignment of Table Mesh Across Viewports

### ISSUE THREAD

**Issue by madmin42** [joysofcode/github-skyline#1]
Hello :]
experimenting with this project, I noticed an issue with the vertical alignment of the 3D table mesh in different viewports. The alignment appears random upon performing a hard reset (F5) after changing browser size. After some debugging I noticed it's about the grid alignment not being aligned the same way as the table mesh. A standard reload doesn't replicate this problem, suggesting it's tied to how the component initializes on first load in new viewports. I've found that moving the grid to the <Align auto> element resolves the issue and the mesh group is always nicely above the grid.

I.e. this example in Scene.svelte
```
<Align auto>
	<Grid 
		infiniteGrid 
		sectionColor="#4a4b4a" 
		sectionSize={20} 
		cellSize={20} 
		fadeDistance={1200} 
	/>
	{#each contributions as row, i}
		{#each row as day, j}
			{#if day}
				{@const color = getColor(day.level)}
				{@const y = normalize(day.count)}
				<T.Group position={[0, 0, 12 * i]} scale.y={$scaleY}>
					<T.Mesh position={[12 * j, y / 2, 0]}>
						<T.BoxGeometry args={[10, y, 10]} />
						<T.MeshStandardMaterial {color} />
					</T.Mesh>
				</T.Group>
			{/if}
		{/each}
	{/each}
</Align>
```

Not sure if you're open to PRs, @mattcroat , may it at least help somebody seeing the same scenario.
Thanks a lot for the guide!

Browser: Mozilla Firefox 118.0.1

**Comment by matiadev** [comment]
Thank you! 😄
